# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:

  - name: Terminal 1
    before: echo 'begin commands'
    init: 
      npm install 
      git clone https://github.com/eclipse/paho.mqtt.python.git
      cd paho.mqtt.python
      python setup.py install
      python pip install scipy
      sudo pip3 install streamlit
      sudo pip install python-git
      
    command: echo 'start script'

  - name: Terminal 2
    before: echo 'begin commands'
    init: 
      sudo pip3 install streamlit-autorefresh
      sudo apt install mosquitto
      sudo apt install mosquitto-clients
      sudo service mosquitto start
      sudo service mosquitto status
      sudo pip3 install paho-mqtt

    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/

ports:
- name: Streamlit
  description: The main application web server
  port: 8501
  onOpen: open-browser
  