# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init:  |
      npm install -g json
      python -m pip install scipy   
      sudo pip3 install streamlit
      sudo pip3 install streamlit-autorefresh
      sudo pip3 install matplotlib
      sudo apt install -y mosquitto
      sudo apt install mosquitto-clients
      sudo service mosquitto start
      sudo service mosquitto status
      sudo pip3 install paho-mqtt
      git clone https://github.com/eclipse/paho.mqtt.python.git
      cd paho.mqtt.python
      python setup.py install
      cd ..
    command: streamlit run app.py

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/

ports:
- name: Streamlit
  description: The main application web server
  port: 8501
  onOpen: open-browser
  